site_name: Memoriai
site_description: The Open-Source Memory Layer for AI Agents & Multi-Agent Systems
site_author: Harshal More
site_url: https://GibsonAI.github.io/memoriai

repo_name: memoriai
repo_url: https://github.com/GibsonAI/memoriai
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Basic Usage: getting-started/basic-usage.md
  - Configuration:
    - Settings: configuration/settings.md
    - Database Setup: configuration/database.md
    - Environment Variables: configuration/environment.md
  - Examples:
    - Basic Example: examples/basic.md
    - Personal Assistant: examples/personal-assistant.md
    - Advanced Config: examples/advanced-config.md
  - API Reference:
    - Core: api/core.md
    - Configuration: api/configuration.md
    - Utils: api/utils.md
  - Integrations:
    - LiteLLM: integrations/litellm.md
    - OpenAI: integrations/openai.md
    - Anthropic: integrations/anthropic.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/memoriai
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/memoriai/